services:
  postgres:
    image: 'postgres:17'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
    ports:
      - ${POSTGRES_PORT}:5432
